apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: shubham-varshney-dev-tls
spec:
  secretName: shubham-varshney-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shubham-varshney.dev
  dnsNames: 
    - shubham-varshney.dev
    - www.shubham-varshney.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shubham-varshney.dev
          - www.shubham-varshney.dev
